sudo: required
services: docker
language: minimal
dist: xenial

# env:
#   - VAR=val

#thanks to https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

cache:
  directories:
    - $HOME/docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblz4-tool
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - curl -Lo dind-cluster-v1.13.sh https://github.com/kubernetes-sigs/kubeadm-dind-cluster/releases/download/v0.1.0/dind-cluster-v1.13.sh
  - chmod +x ./dind-cluster-v1.13.sh 
  - ./dind-cluster-v1.13.sh up

script:
  - ls ~
  - ~/.kubeadm-dind-cluster/kubectl get nodes -o wide
  - ~/.kubeadm-dind-cluster/kubectl get all -o wide --all-namespaces 
  - sudo ps afux  | sort -n -k5 |  awk 'NR>1 {$5=int($5/1024)"M";}{ print;}'
  - free -mh
  - uptime
  - sleep 20
  - uptime
  - sleep 60
  - uptime